name: Docker CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Build & test
        run: |
          npm ci
          npm run build
      - name: Docker Build & Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: todo-next-app:latest
